import { BigNumberish } from "ethers";
import { ethers } from "hardhat";
import { keccak_256, Point } from "@cypher-laboratory/ring-sig-utils";

// eslint-disable-next-line @typescript-eslint/no-var-requires
const { expect } = require("chai");

describe("SAG-EVM-verifier", function () { // todo: add some more tests

  it("Verify a ring signature", async function () {
    // link library
    const contractFactory = await ethers.getContractFactory("SAGVerifier");

    // deploy SigVerifier contract
    const SagVerifier = await contractFactory.deploy();

    const message =
      40340039748299835169756547746037309976814975367605249759025889748097184499642n;

    const ring_: BigNumberish[] = [
      10332262407579932743619774205115914274069865521774281655691935407979316086911n,
      100548694955223641708987702795059132275163693243234524297947705729826773642827n,
      15164162595175125008547705889856181828932143716710538299042410382956573856362n,
      20165396248642806335661137158563863822683438728408180285542980607824890485122n,
      30103554500144535254965021336757008479704861502777924021458799636567575289359n,
      52090609727678693574435399254703833889410700116234244177206170117175907888773n,
    ];

    const responses: BigNumberish[] = [
      11804634253715958305924663675149570036087556552259958445438461057755571312556n,
      54504904582581664190079678841661949924646048914257204184447875552904565842816n,
      39029979142995495559808722560230252062143262593772751292415635904439923318057n,
    ];

    const c: BigNumberish =
      63894040806659059839317990719410380194290503251271615962483579211495165605502n;

    expect(
      await SagVerifier.verifyRingSignature(message, ring_, responses, c),
    ).to.equal(true);
  });

  // this test ensure that this library can always verify a ring signature generated by the latest version of the @cypher-laboratory/alicesring-sag package
  // fails if the library cannot verify the signature
  it("Verify a ring signature from the @cypher-laboratory/alicesring-sag package", async function () {
    // get the valid signature from `packages/sag-ts/test/data/jsonSignatures.json`
    const signature = require("../../sag-ts/test/data/jsonSignatures.json").valid;

    if (!signature) {
      throw new Error("test Signature not found at `packages/sag-ts/test/data/jsonSignatures.json`");
    }

    // compute message digest from signature.message
    const messageDigest: BigNumberish = BigInt("0x" + keccak_256([signature.message as string], true /* evmCompatible */)),
      ring: BigNumberish[] = signature.ring.map((point: string) => [Point.deserialize(point).x, Point.deserialize(point).y]).flat(),
      responses: BigNumberish[] = signature.responses.map((response: string) => BigInt("0x" + response)),
      c: BigNumberish = BigInt("0x" + signature.c);

    // link library
    const contractFactory = await ethers.getContractFactory("SAGVerifier");

    // deploy SigVerifier contract
    const SagVerifier = await contractFactory.deploy();

    expect(
      await SagVerifier.verifyRingSignature(messageDigest, ring, responses, c),
    ).to.equal(true);
  });

  // todo: test all cases (array length, etc) from `packages/sag-ts/test/data/jsonSignatures.json` (except the ones that plays with unexpected types)
});