import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],


  tutorialSidebar: [
    'AlicesRing',
    'ring-signatures',
    {
      type: 'category',
      label: 'SAG',
      items: [
        {
          type: 'doc',
          id: 'SAG/SAG-ts',
          label: 'Typescript',
          className: 'sidebar-item-ts'
        },
        {
          type: 'doc',
          id: 'SAG/SAG-rust-verifier',
          label: 'Rust Verifier',
          className: 'sidebar-item-rs'
        },
        {
          type: 'doc',
          id: 'SAG/SAG-evm-verifier',
          label: 'EVM Verifier',
          className: 'sidebar-item-solidity'
        },
        {
          type: 'doc',
          id: 'SAG/SAG-starknet',
          label: 'SAG for Starknet',
          className: 'sidebar-item-cairo'
        }
      ],
    },
    {
      type: 'category',
      label: 'LSAG',
      items: [
        {
          type: 'doc',
          id: 'LSAG/LSAG-ts',
          label: 'Typescript',
          className: 'sidebar-item-ts'
        },
        {
          type: 'doc',
          id: 'LSAG/LSAG-evm-verifier',
          label: 'EVM Verifier',
          className: 'sidebar-item-solidity'
        },
        {
          type: 'doc',
          id: 'LSAG/LSAG-rust-verifier',
          label: 'Rust Verifier',
          className: 'sidebar-item-rs'
        },
      ],
    },
    {
      type: 'category',
      label: '🦊 Metamask Snap',
      items: [
        {
          type: 'doc',
          id: 'metamask-snap/overview',
          label: 'Overview',
        },
        {
          type: 'doc',
          id: 'metamask-snap/features',
          label: 'Features',
        },
        {
          type: 'doc',
          id: 'metamask-snap/installation',
          label: 'Installation',
        },
        {
          type: 'doc',
          id: 'metamask-snap/usage',
          label: 'Usage',
        },
      ]
    },
    'cypher-lab',
  ],

};

export default sidebars;
