name: Node.js CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build package
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - run: npm i
      - run: npm run build