name: Node.js CI

on:
  push:
  workflow_call:

jobs:
  lintAndTest:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      # Install all dependencies for all packages in the monorepo
      - run: npm ci --workspaces

      # Check formatting for all packages
      - run: npm run fmt:check --workspaces

      # Build all packages
      - run: npm run build 

      # Run tests for all packages
      - run: npm test --workspaces


