

name: Publish Package to npmjs
on:
  release:
    types: [published]
    
jobs:
  test:
    uses: ./.github/workflows/linter&test.yml

  publish-npm:
    needs:
      - test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    # Setup .npmrc file to publish to npm
    - uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        registry-url: 'https://registry.npmjs.org'
    - run: npm ci
    # Ensure the publish script is executable
    - run: chmod +x ./scripts/publish.sh
    # Execute the publish script
    - run: ./scripts/publish.sh stable
      env:
        NODE_AUTH_TOKEN: ${{ secrets.npm_token }}